[JAVA-19] 오류와 예외의 차이점을 설명해주세요
Backend-CS-Interview/tech-interview pull request #11
Opened 2024-09-09 12:49 UTC by SH-Seol

## ❓ Question

에러와 예외를 구분하는 이유를 설명해주세요.
예외의 종류에는 무엇이 있는지 설명해주세요.

## 🔗 Reference

https://inpa.tistory.com/entry/JAVA-%E2%98%95-%EC%97%90%EB%9F%ACError-%EC%99%80-%EC%98%88%EC%99%B8-%ED%81%B4%EB%9E%98%EC%8A%A4Exception-%F0%9F%92%AF-%EC%B4%9D%EC%A0%95%EB%A6%AC

2024-09-12 15:15 UTC, jorippppong approved these changes

2024-09-13 15:37 UTC, Ywoosang requested changes

2024-09-13 15:37 UTC, Ywoosang commented on java_interview.md
> +<summary>오류(Error)와 예외(Exception)의 차이점을 설명해주세요.</summary>
내용이 누락된 것 같아요

2024-09-16 08:12 UTC, SH-Seol commented on java_interview.md
> +<summary>오류(Error)와 예외(Exception)의 차이점을 설명해주세요.</summary>
헉 수정하겠습니다..!

2024-09-19 14:10 UTC, Ywoosang approved these changes

2024-09-23 07:58 UTC, merged