[JAVA-8] wrapper 타입에 대해 설명해주세요
Backend-CS-Interview/tech-interview pull request #2
Opened 2024-09-03 12:49 UTC by Ywoosang

## ❓ Question

자바의 Wrapper 클래스는 무엇이며, 왜 사용하나요?
자바에서 오토박싱과 오토언박싱에 대해 설명해주세요
기본타입과 래퍼타입의 차이점과 어떤 경우에 기본 타입을 사용해야 할 지 설명해 주세요

## 🔗 Reference

2024-09-04 14:22 UTC, jorippppong approved these changes

2024-09-05 06:21 UTC, jorippppong requested changes
꼬리 질문은 토글 내부에 위치시켜주세요!
꼬리 질문은 토글 내부의 토클의 형태로 작성해주시면 됩니다. 리드미에는 '-' 로 되어있는데, 해당 부분은 제가 다음 PR 때 토글 모양으로 수정하도록 하겠습니다.

2024-09-05 13:44 UTC, jorippppong approved these changes

2024-09-05 13:50 UTC, SH-Seol approved these changes

2024-09-05 13:52 UTC, merged