[JAVA-9] Garbage Collection과 Garbage Collector의 차이를 설명해주세요.
Backend-CS-Interview/tech-interview pull request #3
Opened 2024-09-04 06:28 UTC by SH-Seol

## ❓ Question

Garbage Collection과 Garbage Collector의 차이를 설명해주세요.

개발자는 가비지콜렉터만 믿고 메모리를 신경쓰지 않아도 되는 것인가요?

heap의 구조에 대해서 설명해주세요.

가비지 컬렉션의 과정을 설명해주세요.

## 🔗 Reference

https://inpa.tistory.com/entry/JAVA-%E2%98%95-%EA%B0%80%EB%B9%84%EC%A7%80-%EC%BB%AC%EB%A0%89%EC%85%98GC-%EB%8F%99%EC%9E%91-%EC%9B%90%EB%A6%AC-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%F0%9F%92%AF-%EC%B4%9D%EC%A0%95%EB%A6%AC

https://mangkyu.tistory.com/118

2024-09-04 14:22 UTC, jorippppong approved these changes

2024-09-05 06:27 UTC, jorippppong requested changes

2024-09-05 06:27 UTC, jorippppong commented on java_interview.md
> +- 꼬리질문1: 그렇다면 개발자는 가비지콜렉터만 믿고 메모리를 신경쓰지 않아도 되는 것인가요?
꼬리질문도 토글로 수정부탁드립니다!
제가 리드미에 토글 모양이 아닌 '-' 모양으로 표기했네요! 허허 리드미는 제가 다음 PR에 수정해서 올리도록 하겠습니다!

2024-09-05 11:54 UTC, SH-Seol commented on java_interview.md
> +- 꼬리질문1: 그렇다면 개발자는 가비지콜렉터만 믿고 메모리를 신경쓰지 않아도 되는 것인가요?
헉 알겠습니다!

2024-09-05 13:31 UTC, jorippppong submitted a review, later dismissed

2024-09-05 13:54 UTC, Ywoosang approved these changes, later dismissed

2024-09-05 14:23 UTC, jorippppong approved these changes

2024-09-05 14:23 UTC, Ywoosang approved these changes

2024-09-05 14:24 UTC, merged